import React, { useState } from 'react';
import { loadStripe } from '@stripe/stripe-js';
import { Elements, useStripe, useElements } from '@stripe/react-stripe-js';

// Initialize Stripe asynchronously outside the component render loop to prevent re-instantiation
const stripePromise = loadStripe(process.env.REACT_APP_STRIPE_PUBLIC_KEY || 'pk_test_sample_token_abc123');

/**
 * ── Sub-Component: Core Action Button ──
 * Path: client/src/components/finances/StripePayButton.jsx (Internal Button Logic)
 */
function StripeCheckoutForm({ amountInUsd, clientSecret, onPaymentSuccess, onPaymentError }) {
  const stripe = useStripe();
  const elements = useElements();
  const [isProcessing, setIsProcessing] = useState(false);

  const handleStripePayment = async (e) => {
    e.preventDefault();

    if (!stripe || !elements || !clientSecret) {
      // Stripe.js has not loaded yet or backend session is uninitialized
      return;
    }

    setIsProcessing(true);

    try {
      // Confirm the Card Payment using the Client Secret generated by your Node.js backend
      const result = await stripe.confirmCardPayment(clientSecret, {
        payment_method: {
          // 'card' tells Stripe to pull card details automatically from secure input components
          // If using a custom embedded Stripe CardElement, pass it here: card: elements.getElement(CardElement)
          billing_details: {
            name: 'Marketplace Platform User',
          },
        },
      });

      if (result.error) {
        console.error('Stripe Engine Payment Exception:', result.error.message);
        setIsProcessing(false);
        if (onPaymentError) onPaymentError(result.error.message);
      } else {
        if (result.paymentIntent.status === 'succeeded') {
          setIsProcessing(false);
          if (onPaymentSuccess) onPaymentSuccess(result.paymentIntent);
        }
      }
    } catch (err) {
      console.error('Network execution failure during Stripe checkout:', err);
      setIsProcessing(false);
      if (onPaymentError) onPaymentError(err.message);
    }
  };

  return (
    <button
      type="button"
      onClick={handleStripePayment}
      disabled={!stripe || isProcessing}
      style={{
        ...styles.paymentBtn,
        ...((!stripe || isProcessing) ? styles.disabledBtn : {})
      }}
    >
      <span style={styles.icon}>🔒</span>
      {isProcessing ? 'Authorizing Secure Gateway...' : `Pay International Card ($${amountInUsd.toLocaleString()})`}
    </button>
  );
}

/**
 * ── Main Exported Component Wrapper ──
 * Path: client/src/components/finances/StripePayButton.jsx
 * * Wraps the checkout form action within the mandatory Stripe Elements provider frame.
 */
export default function StripePayButton({ 
  amountInUsd = 0, 
  clientSecret = '', 
  onPaymentSuccess, 
  onPaymentError 
}) {
  return (
    <Elements stripe={stripePromise}>
      <StripeCheckoutForm 
        amountInUsd={amountInUsd} 
        clientSecret={clientSecret} 
        onPaymentSuccess={onPaymentSuccess} 
        onPaymentError={onPaymentError} 
      />
    </Elements>
  );
}

// ── Styles ────────────────────────────────────────────────────────────────────
const styles = {
  paymentBtn: {
    background: '#635BFF', // Official Stripe Branding Indigo Blur Token
    color: '#ffffff',
    border: '1px solid #4F46E5',
    borderRadius: '8px',
    padding: '12px 24px',
    fontSize: '14.5px',
    fontWeight: 700,
    cursor: 'pointer',
    display: 'inline-flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: '10px',
    fontFamily: "'DM Sans', system-ui, sans-serif",
    boxSizing: 'border-box',
    width: '100%',
    transition: 'background 0.15s ease, transform 0.1s ease',
    boxShadow: '0 4px 14px rgba(99, 91, 255, 0.25)',
  },
  disabledBtn: {
    background: '#1E293B',
    borderColor: '#334155',
    color: '#64748B',
    cursor: 'not-allowed',
    boxShadow: 'none',
  },
  icon: {
    fontSize: '15px',
  }
};